VENV_DIR = ${DOTFILES_DIR}/scripts/.venv
VENV_PIP = ${VENV_DIR}/bin/pip
VENV_PYTHON = ${VENV_DIR}/bin/python

DOTFILES_DIR = ${CURDIR}

FONTS_SRC = ${DOTFILES_DIR}/fonts
FONTS_DEST = ${HOME}/.local/share/fonts
